include:
  - component: "$CI_SERVER_FQDN/it-erben/utilities/pdf-publisher/build-publish@1.5.1"
  - component: "$CI_SERVER_FQDN/it-erben/utilities/verifications/lychee-lint@1.0.0"
  - component: "$CI_SERVER_FQDN/it-erben/utilities/verifications/yaml-lint@1.0.0"
  - component: "$CI_SERVER_FQDN/it-erben/utilities/verifications/markdown-lint@1.0.0"

stages:
  - build
  - lint
  - verify
  - release
  - deploy
