include:
  - component: "$CI_SERVER_FQDN/it-erben/utilities/pdf-publisher/build-publish@1.4.0"

stages:
  - build
  - verify
  - release
  - deploy

maven-verify:
  stage: verify
  image: maven:3.9-eclipse-temurin-21
  variables:
    MAVEN_REPO_LOCAL: "$CI_PROJECT_DIR/.m2/repository"
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .m2/repository
    policy: pull-push
  script:
    - mvn -B -ntp -Dmaven.repo.local="$MAVEN_REPO_LOCAL" verify
  artifacts:
    when: always
    paths:
      - target/surefire-reports
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
