<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tech.erben</groupId>
        <artifactId>trainer</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>jigsaw-greetings-app</artifactId>
    <name>Trainer: Jigsaw Greetings App</name>
    <description>Konsolenbeispiel, das das Jigsaw-Greetings-Modul nutzt</description>

    <dependencies>
        <dependency>
            <groupId>tech.erben</groupId>
            <artifactId>jigsaw-greetings-module</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <mainClass>tech.erben.gfu.jigsaw.app.ConsoleApp</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
