<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>tech.erben</groupId>
        <artifactId>java17-course</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <groupId>tech.erben</groupId>
    <artifactId>solutions</artifactId>
    <packaging>pom</packaging>
    <name>Solutions</name>

    <modules>
        <module>records-car-dealership-solution</module>
        <module>text-blocks-barbershop-solution</module>
        <module>food-delivery-modern-java-solution</module>
        <module>sealed-classes-insurance-solutions</module>
        <module>enhanced-npe-helpdesk-solution</module>
        <module>random-generator-raffle-solution</module>
    </modules>
</project>
